config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  resources :memories
  devise_scope :user do
    get "/login" => "users/sessions#new"
    delete "/logout" => "users/sessions#destroy"
    get "/register" => "users/registrations#new"
    get "/edit_profile" => "users/registrations#edit"
  end
  authenticate :user do
    resources :stories, only: [:new, :create, :edit, :update, :destroy]
    resources :memories, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :stories, only: [:index, :show]
  resources :memories, only: [:index, :show]
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About Stories</h1>

<p>
  This web application was made so that I could easily 
  record memories and revisit them. <br/> <br/> Think of it as a 
  digital photo album that lets you travel back in time
  to parts of your life in chronological order - and easily share
  your story with others.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact Me</h1>

<p>
  Have feedback? Want a feature added? Is something broken? <br/>
  Let me know at cloudismydog@gmail.com.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>Help</h1>

<p>
  There isn't much here yet - eventually I'll add a FAQ section.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="center jumbotron">
  <h1>Stories</h1>

  <h2>
    What's your story?
  </h2>

  <% if current_user != nil %>
    <%= link_to "Add Story", new_story_path, class: "btn btn-lg btn-primary" %>
  <% else %>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>