config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  resources :memories
  devise_scope :user do
    get "/login" => "users/sessions#new"
    delete "/logout" => "users/sessions#destroy"
    get "/register" => "users/registrations#new"
    get "/edit_profile" => "users/registrations#edit"
  end
  authenticate :user do
    resources :stories, only: [:new, :create, :edit, :update, :destroy]
    resources :memories, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :stories, only: [:index, :show]
  resources :memories, only: [:index, :show]
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/memory.rb
class Memory < ApplicationRecord
  mount_uploader :image, MemoryUploader

  belongs_to :user
  belongs_to :story

  validates_integrity_of :image
  validates_processing_of :image
  validates_presence_of :name, :date, :image
  validates_length_of :name, minimum: 1, maximum: 255, on: :create
  validates_length_of :description, maximum: 1000, on: :create

  def update_description(description)
    self.description = description
  end
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  def new
    @memory = Memory.new
  end

  def create
    @new_memory = Memory.new(
      name: name(params),
      description: description(params),
      date: date(params),
      image: params[:memory][:image],
      story_id: params[:memory][:story_id],
      user_id: current_user_id
    )

    @new_memory.save

    if @new_memory.valid?
      redirect_to memories_path
    else
      @memory = @new_memory
      render :new
    end
  end

  def index
    @memories = Memory.all
  end

  private

  def current_user_id
    current_user.id
  end

  def date(params)
    params[:memory][:date].blank? ? Date.today : params[:memory][:date]
  end

  def name(params)
    params[:memory][:name].blank? ? date(params) : params[:memory][:name]
  end

  def description(params)
    params[:memory][:description].blank? ? nil : params[:memory][:description]
  end
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/views/memories/index.html.erb
<% provide(:title, "All Memories") %>

<h1>All Memories</h1>

<% if current_user != nil %>
  <%= link_to "Add Memory", new_memory_path, class: "btn btn-lg btn-primary" %>
<% end %>

<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Date</td>
      <td>Owner</td>
      <td>Description</td>
      <td>Image</td>
      <td>Story</td>
    </tr>
  </thead>
  <tbody>
    <% @memories.each do |memory| %>
      <tr class="memory-row" id="<%= dom_id(memory) %>">
        <td class="name"><%= memory.name %></td>
        <td class="date"><%= memory.date %></td>
        <td class="username"><%= memory.user.username %></td>
        <td class="description"><%= memory.description %></td>
        <td class="image">
        <% if memory.image.profile.url.present? %>
          <%= link_to memory.image.profile.url do %>
            <%= image_tag memory.image.profile.url %><br />
          <% end %>
        <% end %>
        </td>
        <td class="story"><%= memory.story.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/memories/new.html.erb
<% provide(:title, "New Memory") %>

<h1>Add a memory to a story</h1>

<%= form_for(@memory) do |f| %>
  <%= f.label(:name) %>
  <%= f.text_field :name %>
  <br />
  <%= f.label(:description) %>
  <%= f.text_field :description %>
  <br />
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image, :required => true %>
    <%= f.hidden_field :image_cache %>
  </div>
  <br />
  <%= f.label(:date) %>
  <%= f.date_field :date %>
  <br />
  <%= f.label(:story_id) %>
  <%= f.select :story_id, options_from_collection_for_select(Story.where(user_id: current_user.id), 'id', 'name') %>
  <br />
  <%= f.submit "Create Memory" %>
<% end %>