config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  resources :memories
  devise_scope :user do
    get "/login" => "users/sessions#new"
    delete "/logout" => "users/sessions#destroy"
    get "/register" => "users/registrations#new"
    get "/edit_profile" => "users/registrations#edit"
  end
  authenticate :user do
    resources :stories, only: [:new, :create, :edit, :update, :destroy]
    resources :memories, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :stories, only: [:index, :show]
  resources :memories, only: [:index, :show]
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Stories
    by <a href="http://www.github.com/JolliestJames">James Martinez</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse header">
  <div class="container">
    <%= link_to "Stories", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path, id: 'link' %></li>
        <li><%= link_to 'Stories', stories_path, id: 'link' %></li>
        <li><%= link_to 'Memories', memories_path, id: 'link' %></li>
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.username %></strong>.
          <li><%= link_to 'Edit profile', edit_profile_path, id: 'link' %></li>
          <li><%= link_to "Logout", logout_path, method: :delete, id: 'link'  %></li>
        <% else %>
          <li><%= link_to "Log in", login_path, id: 'link' %></li>
          <li><%= link_to "Register", register_path, id: 'link' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class = "container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>